/*
 * mayhem-b200 — APRS RX decoder tests.
 *
 * Everything here is checked against the protocol, not against whatever the
 * implementation happens to produce:
 *
 *  - The FCS is cross-checked three ways: an independent reference that is
 *    upstream's own reflected-0x8408 table algorithm (with the first entries
 *    compared literally against firmware/baseband/proc_aprsrx.hpp), the
 *    published CRC-16/X-25 check value for "123456789" (0x906E), and the
 *    residue test the receiver actually performs.
 *  - The AX.25 bit stream is generated by an encoder transcribed from
 *    firmware/application/protocols/ax25.cpp — same LSB-first byte order, same
 *    five-ones stuffing, same NRZI sense — so the decoder is verified against
 *    upstream's transmitter, not against itself.
 *  - Positions are checked against the arithmetic in the APRS 1.0.1
 *    specification, computed by hand in the test.
 *  - The AFSK path is verified by synthesising a Bell 202 signal with
 *    dsp::afsk_modulate and decoding it back, and the whole channel decoder by
 *    FM-modulating that audio onto a complex carrier at an offset.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include "test_main.hpp"

#include "app_registry.hpp"
#include "bitmaps.hpp"
#include "demod_digital.hpp"
#include "ui_aprs_rx.hpp"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <string>
#include <vector>

using app::AprsChannelDecoder;
using app::AprsPacket;
using app::AprsPosition;
using app::Ax25Decoder;

namespace {

constexpr double kPi = 3.14159265358979323846;

/* --- Reference FCS ---------------------------------------------------------
 *
 * Upstream's crc_ccitt_tab (firmware/baseband/proc_aprsrx.hpp) is the standard
 * reflected CRC-CCITT table; this rebuilds it and the running loop that uses
 * it. The first entries are compared against upstream's literals below. */

struct ReferenceCrc {
    uint16_t tab[256];

    ReferenceCrc() {
        for (int i = 0; i < 256; i++) {
            uint16_t crc = static_cast<uint16_t>(i);
            for (int b = 0; b < 8; b++) {
                crc = (crc & 1) ? static_cast<uint16_t>((crc >> 1) ^ 0x8408)
                                : static_cast<uint16_t>(crc >> 1);
            }
            tab[i] = crc;
        }
    }

    /* Upstream's parse_packet() loop, verbatim. */
    uint16_t running(const uint8_t* data, size_t length) const {
        uint16_t crc = 0xFFFF;
        for (size_t i = 0; i < length; i++) {
            crc = static_cast<uint16_t>(((crc >> 8) ^ tab[(crc ^ data[i]) & 0xFF]) & 0xFFFF);
        }
        return crc;
    }

    /* What a transmitter appends: upstream's CRC<16,true,true> checksum(). */
    uint16_t fcs(const uint8_t* data, size_t length) const {
        return static_cast<uint16_t>(running(data, length) ^ 0xFFFF);
    }
};

const ReferenceCrc& reference_crc() {
    static const ReferenceCrc r;
    return r;
}

/* --- AX.25 frame construction ---------------------------------------------- */

/* One shifted AX.25 address octet group. Upstream builds these in
 * application/protocols/aprs.cpp as (ssid | 0x30) then shifted left by one,
 * with the extension bit set on the last address — i.e. 0x60 | ssid<<1 | last. */
std::vector<uint8_t> address(const std::string& call, uint8_t ssid, bool last) {
    std::vector<uint8_t> out;
    std::string c = call;
    c.resize(6, ' ');
    for (size_t i = 0; i < 6; i++) out.push_back(static_cast<uint8_t>(c[i] << 1));
    out.push_back(static_cast<uint8_t>(0x60 | ((ssid & 0x0F) << 1) | (last ? 1 : 0)));
    return out;
}

void append(std::vector<uint8_t>& dst, const std::vector<uint8_t>& src) {
    dst.insert(dst.end(), src.begin(), src.end());
}

void append(std::vector<uint8_t>& dst, const std::string& src) {
    for (char c : src) dst.push_back(static_cast<uint8_t>(c));
}

/* The reference APRS frame used throughout:
 *     N0CALL-9>APRS,WIDE1-1:!4903.50N/07201.75W-Test
 * Position is 49 deg 03.50' N, 72 deg 01.75' W, symbol '/' '-' (house). */
std::vector<uint8_t> reference_frame_body() {
    std::vector<uint8_t> f;
    append(f, address("APRS", 0, false));
    append(f, address("N0CALL", 9, false));
    append(f, address("WIDE1", 1, true));
    f.push_back(0x03);  /* UI control */
    f.push_back(0xF0);  /* PID: no layer 3 */
    append(f, "!4903.50N/07201.75W-Test");
    return f;
}

/* Body plus its FCS, low byte first — the buffer the receiver assembles. */
std::vector<uint8_t> with_fcs(std::vector<uint8_t> body) {
    const uint16_t fcs = reference_crc().fcs(body.data(), body.size());
    body.push_back(static_cast<uint8_t>(fcs & 0xFF));
    body.push_back(static_cast<uint8_t>((fcs >> 8) & 0xFF));
    return body;
}

/* --- HDLC / NRZI encoder ---------------------------------------------------
 *
 * Transcribed from firmware/application/protocols/ax25.cpp (AX25Frame): bytes
 * least-significant bit first, a stuffed zero after five consecutive ones
 * (never inside a flag), NRZI where a data 0 flips the line. Emits one line
 * level per bit — exactly what the AFSK modulator and the decoder consume. */
class Ax25Encoder {
   public:
    void add_flag() { add_byte(0x7E, true); }
    void add_data(uint8_t byte) { add_byte(byte, false); }

    void add_frame(const std::vector<uint8_t>& body, size_t lead_flags = 8,
                   size_t trail_flags = 2, bool corrupt_fcs = false) {
        for (size_t i = 0; i < lead_flags; i++) add_flag();
        for (uint8_t b : body) add_data(b);

        uint16_t fcs = reference_crc().fcs(body.data(), body.size());
        if (corrupt_fcs) fcs = static_cast<uint16_t>(fcs ^ 0x0001);
        add_data(static_cast<uint8_t>(fcs & 0xFF));
        add_data(static_cast<uint8_t>((fcs >> 8) & 0xFF));

        for (size_t i = 0; i < trail_flags; i++) add_flag();
    }

    /* Seven ones with no stuffing: the HDLC abort sequence. */
    void add_abort() {
        for (int i = 0; i < 7; i++) nrzi_add(1);
        nrzi_add(0);
        ones_ = 0;
    }

    const std::vector<uint8_t>& bits() const { return bits_; }

   private:
    void nrzi_add(uint8_t bit) {
        if (!bit) level_ ^= 1;
        bits_.push_back(level_);
    }

    void add_byte(uint8_t byte, bool is_flag) {
        for (int i = 0; i < 8; i++) {
            const uint8_t bit = static_cast<uint8_t>((byte >> i) & 1);
            nrzi_add(bit);
            if (bit) {
                ones_++;
                if (ones_ == 5 && !is_flag) {
                    nrzi_add(0);
                    ones_ = 0;
                }
            } else {
                ones_ = 0;
            }
        }
    }

    std::vector<uint8_t> bits_{};
    uint8_t level_{0};
    uint8_t ones_{0};
};

/* Collects every frame a decoder emits. */
struct FrameSink {
    std::vector<std::vector<uint8_t>> frames;

    void attach(Ax25Decoder& d) {
        d.set_frame_handler([this](const uint8_t* p, size_t n) {
            frames.emplace_back(p, p + n);
        });
    }
};

std::string hex(const std::vector<uint8_t>& v) {
    static const char* digits = "0123456789ABCDEF";
    std::string s;
    for (uint8_t b : v) {
        s += digits[b >> 4];
        s += digits[b & 0x0F];
    }
    return s;
}

AprsPacket packet_from(const std::vector<uint8_t>& bytes) {
    AprsPacket p;
    p.set_bytes(bytes.data(), bytes.size());
    return p;
}

}  // namespace

/* ===========================================================================
 * FCS
 * ===========================================================================*/

TEST(aprs_reference_crc_table_matches_upstream) {
    /* Literal values from firmware/baseband/proc_aprsrx.hpp crc_ccitt_tab. */
    const uint16_t expected[8] = {0x0000, 0x1189, 0x2312, 0x329b,
                                  0x4624, 0x57ad, 0x6536, 0x74bf};
    for (int i = 0; i < 8; i++) CHECK_EQ(reference_crc().tab[i], expected[i]);

    /* ...and a few from further in, to catch a table generated with the wrong
     * polynomial that happens to agree on the first few entries. */
    CHECK_EQ(reference_crc().tab[16], 0x1081);
    CHECK_EQ(reference_crc().tab[255], 0x0f78);
}

TEST(aprs_fcs_check_vector) {
    const uint8_t check[] = {'1', '2', '3', '4', '5', '6', '7', '8', '9'};

    /* CRC-16/X-25's published check value. */
    CHECK_EQ(app::ax25_fcs(check, sizeof(check)), 0x906Eu);
    /* ...and upstream's own algorithm agrees. */
    CHECK_EQ(app::ax25_fcs(check, sizeof(check)), reference_crc().fcs(check, sizeof(check)));
}

TEST(aprs_fcs_known_frame) {
    const auto body = reference_frame_body();
    /* 3 x 7 address bytes + control + PID + 24 information bytes. */
    CHECK_EQ(body.size(), 47u);

    const uint16_t mine = app::ax25_fcs(body.data(), body.size());
    const uint16_t theirs = reference_crc().fcs(body.data(), body.size());
    CHECK_EQ(mine, theirs);

    /* The receiver's residue test over data + FCS. */
    const auto framed = with_fcs(body);
    CHECK_EQ(reference_crc().running(framed.data(), framed.size()), 0xF0B8u);
    CHECK(app::ax25_frame_valid(framed.data(), framed.size()));
}

TEST(aprs_fcs_rejects_corruption) {
    const auto framed = with_fcs(reference_frame_body());

    /* Every single-byte corruption must be caught. */
    for (size_t i = 0; i < framed.size(); i++) {
        auto bad = framed;
        bad[i] = static_cast<uint8_t>(bad[i] ^ 0x01);
        CHECK(!app::ax25_frame_valid(bad.data(), bad.size()));
    }

    /* Truncation, and degenerate lengths. */
    CHECK(!app::ax25_frame_valid(framed.data(), framed.size() - 1));
    CHECK(!app::ax25_frame_valid(framed.data(), 1));
    CHECK(!app::ax25_frame_valid(framed.data(), 0));
    CHECK(!app::ax25_frame_valid(nullptr, 10));
}

/* ===========================================================================
 * Address (callsign shift) decoding
 * ===========================================================================*/

TEST(aprs_callsign_shift_decode) {
    const auto packet = packet_from(with_fcs(reference_frame_body()));

    CHECK_STR_EQ(packet.get_destination_formatted(), "APRS");
    CHECK_STR_EQ(packet.get_source_formatted(), "N0CALL-9");
    CHECK_STR_EQ(packet.get_digipeaters_formatted(), ",WIDE1-1");
    CHECK_EQ(packet.get_number_of_digipeaters(), 1u);

    /* The RecentEntries key is the seven raw source bytes, little-endian. */
    uint64_t expected_key = 0;
    const auto src = address("N0CALL", 9, false);
    for (size_t i = 0; i < src.size(); i++)
        expected_key |= static_cast<uint64_t>(src[i]) << (i * 8);
    CHECK_EQ(packet.get_source(), expected_key);
}

TEST(aprs_callsign_ssid_zero_and_two_digit) {
    /* SSID 0 is omitted for source and destination, shown for digipeaters. */
    std::vector<uint8_t> f;
    append(f, address("APZ001", 0, false));
    append(f, address("MB7U", 0, false));
    append(f, address("WIDE2", 0, false));
    append(f, address("ECHO", 15, true));
    f.push_back(0x03);
    f.push_back(0xF0);
    append(f, ">status");

    const auto packet = packet_from(with_fcs(f));

    CHECK_STR_EQ(packet.get_destination_formatted(), "APZ001");
    CHECK_STR_EQ(packet.get_source_formatted(), "MB7U");
    CHECK_STR_EQ(packet.get_digipeaters_formatted(), ",WIDE2-0,ECHO-15");
    CHECK_EQ(packet.get_number_of_digipeaters(), 2u);
}

TEST(aprs_no_digipeaters) {
    std::vector<uint8_t> f;
    append(f, address("APRS", 0, false));
    append(f, address("N0CALL", 0, true));
    f.push_back(0x03);
    f.push_back(0xF0);
    append(f, "=4903.50N/07201.75W-");

    const auto packet = packet_from(with_fcs(f));

    CHECK_STR_EQ(packet.get_digipeaters_formatted(), "");
    CHECK_EQ(packet.get_number_of_digipeaters(), 0u);
    /* 14 address bytes + control + PID */
    CHECK_EQ(packet.get_information_start_index(), 16u);
    CHECK_STR_EQ(packet.get_information_text_formatted(), "=4903.50N/07201.75W-");
}

TEST(aprs_stream_text) {
    const auto packet = packet_from(with_fcs(reference_frame_body()));

    CHECK_EQ(packet.get_information_start_index(), 23u);  /* 14 + 7 + 2 */
    CHECK_STR_EQ(packet.get_information_text_formatted(), "!4903.50N/07201.75W-Test");
    CHECK_STR_EQ(packet.get_stream_text(),
                 "N0CALL-9>APRS,WIDE1-1:!4903.50N/07201.75W-Test");
}

/* ===========================================================================
 * Position parsing
 * ===========================================================================*/

TEST(aprs_position_uncompressed) {
    const auto packet = packet_from(with_fcs(reference_frame_body()));

    CHECK_EQ(packet.get_data_type_identifier(), '!');
    CHECK(packet.has_position());

    const AprsPosition pos = packet.get_position();

    /* 49 deg 03.50' N, 72 deg 01.75' W, straight from the APRS spec's
     * DDMM.hh form. */
    CHECK_NEAR(pos.latitude, 49.0 + 3.50 / 60.0, 1e-5);
    CHECK_NEAR(pos.longitude, -(72.0 + 1.75 / 60.0), 1e-5);
    CHECK_EQ(pos.sym_table_id, static_cast<uint8_t>('/'));
    CHECK_EQ(pos.symbol_code, static_cast<uint8_t>('-'));
}

TEST(aprs_position_southern_eastern_hemisphere) {
    std::vector<uint8_t> f;
    append(f, address("APRS", 0, false));
    append(f, address("VK2XYZ", 0, true));
    f.push_back(0x03);
    f.push_back(0xF0);
    /* '@' carries a 7-character timestamp before the position. */
    append(f, "@092345z3352.10S/15112.90E>Sydney");

    const auto packet = packet_from(with_fcs(f));

    CHECK_EQ(packet.get_data_type_identifier(), '@');
    CHECK(packet.has_position());

    const AprsPosition pos = packet.get_position();
    CHECK_NEAR(pos.latitude, -(33.0 + 52.10 / 60.0), 1e-5);
    CHECK_NEAR(pos.longitude, 151.0 + 12.90 / 60.0, 1e-5);
    CHECK_EQ(pos.symbol_code, static_cast<uint8_t>('>'));
}

TEST(aprs_position_compressed) {
    /* APRS 1.0.1 chapter 9: /YYYYXXXX$cs T, base 91 with an offset of 33.
     *   lat = 90 - (y1*91^3 + y2*91^2 + y3*91 + y4) / 380926
     *   lon = -180 + (x1*91^3 + x2*91^2 + x3*91 + x4) / 190463
     * "<*e7" and "_flL" are the specification's own worked example, which it
     * states decodes to 49 deg 30.00' N, 72 deg 45.00' W. */
    std::vector<uint8_t> f;
    append(f, address("APRS", 0, false));
    append(f, address("N0CALL", 0, true));
    f.push_back(0x03);
    f.push_back(0xF0);
    append(f, "!/5L!!<*e7> sT");

    const auto packet = packet_from(with_fcs(f));
    CHECK(packet.has_position());

    const AprsPosition pos = packet.get_position();

    /* Recompute the spec formula here rather than trusting the decoder. */
    const std::string lat_chars = "5L!!";
    const std::string lon_chars = "<*e7";
    double y = 0.0;
    double x = 0.0;
    for (int i = 0; i < 4; i++) {
        y = y * 91.0 + (lat_chars[static_cast<size_t>(i)] - 33);
        x = x * 91.0 + (lon_chars[static_cast<size_t>(i)] - 33);
    }
    const double expected_lat = 90.0 - y / 380926.0;
    const double expected_lon = -180.0 + x / 190463.0;

    /* Tight enough to catch a missing "- 33" on the fourth base-91 digit, which
     * biases latitude by 33/380926 = 8.7e-5 and longitude by 33/190463 = 1.7e-4
     * degrees. Float precision at these magnitudes is around 3e-6. */
    CHECK_NEAR(pos.latitude, expected_lat, 3e-5);
    CHECK_NEAR(pos.longitude, expected_lon, 3e-5);

    /* And the spec's stated answer for this example. */
    CHECK_NEAR(pos.latitude, 49.5, 1e-3);
    CHECK_NEAR(pos.longitude, -72.75, 1e-3);

    CHECK_EQ(pos.sym_table_id, static_cast<uint8_t>('/'));
    CHECK_EQ(pos.symbol_code, static_cast<uint8_t>('>'));
}

TEST(aprs_position_mic_e) {
    /* Mic-E hides the latitude in the (shifted) destination address and the
     * longitude in the first three information bytes.
     *
     * Destination "335WWU" decodes digit by digit to 3,3,5,7,7,5 — i.e.
     * 33 deg 57.75'. Characters in the P-Z range carry the flags: position 4
     * ('W') says northern hemisphere, position 5 ('W') adds the +100 degree
     * longitude offset, position 6 ('U') says western hemisphere.
     *
     * Longitude bytes are (deg + 28 - offset), (min + 28), (hundredths + 28),
     * so 112 deg 08.90' W is 40, 36, 118. */
    std::vector<uint8_t> dest;
    const std::string mic_e_dest = "335WWU";
    for (char c : mic_e_dest) dest.push_back(static_cast<uint8_t>(c << 1));
    dest.push_back(static_cast<uint8_t>(0x60 | (0 << 1) | 0));

    std::vector<uint8_t> f;
    append(f, dest);
    append(f, address("N0CALL", 7, true));
    f.push_back(0x03);
    f.push_back(0xF0);
    f.push_back(static_cast<uint8_t>('`'));  /* Mic-E current data */
    f.push_back(static_cast<uint8_t>(112 + 28 - 100));
    f.push_back(static_cast<uint8_t>(8 + 28));
    f.push_back(static_cast<uint8_t>(90 + 28));
    append(f, "/]\"4V}");

    const auto packet = packet_from(with_fcs(f));

    CHECK_EQ(packet.get_data_type_identifier(), '`');
    CHECK(packet.has_position());

    const AprsPosition pos = packet.get_position();
    CHECK_NEAR(pos.latitude, 33.0 + 57.75 / 60.0, 1e-4);
    CHECK_NEAR(pos.longitude, -(112.0 + 8.90 / 60.0), 1e-4);
}

TEST(aprs_position_absent_for_status_packet) {
    std::vector<uint8_t> f;
    append(f, address("APRS", 0, false));
    append(f, address("N0CALL", 0, true));
    f.push_back(0x03);
    f.push_back(0xF0);
    append(f, ">Just a status, no position");

    const auto packet = packet_from(with_fcs(f));

    CHECK_EQ(packet.get_data_type_identifier(), '>');
    CHECK(!packet.has_position());

    /* get_position() must still be safe to call, and yield nothing. */
    const AprsPosition pos = packet.get_position();
    CHECK_EQ(pos.latitude, 0.0f);
    CHECK_EQ(pos.longitude, 0.0f);
}

TEST(aprs_malformed_packets_do_not_crash) {
    /* Empty. */
    AprsPacket empty;
    CHECK_EQ(empty.size(), 0u);
    CHECK_STR_EQ(empty.get_source_formatted(), "");
    CHECK_STR_EQ(empty.get_information_text_formatted(), "");
    CHECK_EQ(empty.get_data_type_identifier(), '\0');
    CHECK(!empty.has_position());
    (void)empty.get_position();
    (void)empty.get_stream_text();

    /* Shorter than a single address. */
    const uint8_t stub[] = {0x82, 0xA0, 0xA4};
    AprsPacket tiny;
    tiny.set_bytes(stub, sizeof(stub));
    CHECK_EQ(tiny.size(), 3u);
    (void)tiny.get_stream_text();
    (void)tiny.get_position();

    /* A position identifier with a truncated position field. */
    std::vector<uint8_t> f;
    append(f, address("APRS", 0, false));
    append(f, address("N0CALL", 0, true));
    f.push_back(0x03);
    f.push_back(0xF0);
    append(f, "!4903.5");

    const auto packet = packet_from(with_fcs(f));
    CHECK(packet.has_position());
    const AprsPosition pos = packet.get_position();
    CHECK_EQ(pos.latitude, 0.0f);  /* refused rather than half-parsed */

    /* Oversized input is clamped to the 256-byte buffer upstream uses. */
    std::vector<uint8_t> huge(1000, 0x41);
    AprsPacket big;
    big.set_bytes(huge.data(), huge.size());
    CHECK_EQ(big.size(), app::kAprsMaxLength);
}

/* ===========================================================================
 * HDLC bit decoding
 * ===========================================================================*/

TEST(ax25_decoder_decodes_a_frame) {
    Ax25Encoder enc;
    enc.add_frame(reference_frame_body());

    Ax25Decoder dec;
    FrameSink sink;
    sink.attach(dec);
    dec.feed_bits(enc.bits());

    CHECK_EQ(sink.frames.size(), 1u);
    CHECK_EQ(dec.frames_valid(), 1u);
    CHECK_EQ(dec.frames_bad_fcs(), 0u);

    if (!sink.frames.empty()) {
        CHECK_STR_EQ(hex(sink.frames[0]), hex(with_fcs(reference_frame_body())));

        const auto packet = packet_from(sink.frames[0]);
        CHECK_STR_EQ(packet.get_stream_text(),
                     "N0CALL-9>APRS,WIDE1-1:!4903.50N/07201.75W-Test");
    }
}

TEST(ax25_decoder_destuffs_five_ones) {
    /* 0x3F, 0x7C and 0x1F all carry five-or-more consecutive ones in the
     * least-significant-bit-first order AX.25 transmits, so the encoder has to
     * stuff and the decoder has to remove the stuffing. */
    std::vector<uint8_t> f;
    append(f, address("APRS", 0, false));
    append(f, address("N0CALL", 0, true));
    f.push_back(0x03);
    f.push_back(0xF0);
    f.push_back(0x3F);
    f.push_back(0x7C);
    f.push_back(0x1F);
    f.push_back(0xFF);
    append(f, "stuffing");

    Ax25Encoder enc;
    enc.add_frame(f);

    /* The stream must be longer than 8 bits per byte: stuffing happened. */
    const size_t unstuffed_bits = (8 + f.size() + 2 + 2) * 8;
    CHECK(enc.bits().size() > unstuffed_bits);

    Ax25Decoder dec;
    FrameSink sink;
    sink.attach(dec);
    dec.feed_bits(enc.bits());

    CHECK_EQ(sink.frames.size(), 1u);
    if (!sink.frames.empty()) CHECK_STR_EQ(hex(sink.frames[0]), hex(with_fcs(f)));
}

TEST(ax25_decoder_rejects_bad_fcs) {
    Ax25Encoder enc;
    enc.add_frame(reference_frame_body(), 8, 2, /*corrupt_fcs=*/true);

    Ax25Decoder dec;
    FrameSink sink;
    sink.attach(dec);
    dec.feed_bits(enc.bits());

    CHECK_EQ(sink.frames.size(), 0u);
    CHECK_EQ(dec.frames_valid(), 0u);
    CHECK_EQ(dec.frames_bad_fcs(), 1u);
}

TEST(ax25_decoder_rejects_runt_frame) {
    /* Fewer than kAprsMinLength bytes between two flags: not a frame. */
    Ax25Encoder enc;
    enc.add_flag();
    enc.add_flag();
    const std::vector<uint8_t> runt{0x82, 0xA0, 0xA4, 0xA6};
    for (uint8_t b : runt) enc.add_data(b);
    enc.add_flag();

    Ax25Decoder dec;
    FrameSink sink;
    sink.attach(dec);
    dec.feed_bits(enc.bits());

    CHECK_EQ(sink.frames.size(), 0u);
    CHECK_EQ(dec.frames_too_short(), 1u);
}

TEST(ax25_decoder_handles_abort_sequence) {
    Ax25Encoder enc;
    enc.add_flag();
    enc.add_flag();
    for (uint8_t b : reference_frame_body()) enc.add_data(b);
    enc.add_abort();  /* seven ones: throw the partial frame away */
    enc.add_frame(reference_frame_body(), 4, 2);

    Ax25Decoder dec;
    FrameSink sink;
    sink.attach(dec);
    dec.feed_bits(enc.bits());

    /* Only the frame that came after the abort survives. */
    CHECK_EQ(sink.frames.size(), 1u);
    if (!sink.frames.empty()) CHECK_STR_EQ(hex(sink.frames[0]), hex(with_fcs(reference_frame_body())));
}

TEST(ax25_decoder_back_to_back_frames_share_a_flag) {
    /* Two frames separated by exactly one flag. Upstream drops both because it
     * never clears packet_buffer_size after emitting; see the departure note in
     * ui_aprs_rx.hpp. */
    auto body_a = reference_frame_body();

    std::vector<uint8_t> body_b;
    append(body_b, address("APRS", 0, false));
    append(body_b, address("M0ABC", 3, true));
    body_b.push_back(0x03);
    body_b.push_back(0xF0);
    append(body_b, "=5132.07N/00007.42W-London");

    Ax25Encoder enc;
    enc.add_frame(body_a, 8, 1);   /* one trailing flag ... */
    enc.add_frame(body_b, 0, 2);   /* ... which opens the next frame */

    Ax25Decoder dec;
    FrameSink sink;
    sink.attach(dec);
    dec.feed_bits(enc.bits());

    CHECK_EQ(sink.frames.size(), 2u);
    if (sink.frames.size() == 2) {
        CHECK_STR_EQ(hex(sink.frames[0]), hex(with_fcs(body_a)));
        CHECK_STR_EQ(hex(sink.frames[1]), hex(with_fcs(body_b)));

        const auto second = packet_from(sink.frames[1]);
        CHECK_STR_EQ(second.get_source_formatted(), "M0ABC-3");
        CHECK_NEAR(second.get_position().latitude, 51.0 + 32.07 / 60.0, 1e-5);
        CHECK_NEAR(second.get_position().longitude, -(0.0 + 7.42 / 60.0), 1e-5);
    }
}

TEST(ax25_decoder_ignores_noise_before_sync) {
    /* An arbitrary run of levels ahead of the preamble must not produce a
     * frame, and must not stop the real one being decoded. */
    Ax25Decoder dec;
    FrameSink sink;
    sink.attach(dec);

    uint32_t lfsr = 0xACE1u;
    for (int i = 0; i < 4000; i++) {
        const uint32_t bit = ((lfsr >> 0) ^ (lfsr >> 2) ^ (lfsr >> 3) ^ (lfsr >> 5)) & 1u;
        lfsr = (lfsr >> 1) | (bit << 15);
        dec.feed_bit(static_cast<uint8_t>(lfsr & 1u));
    }

    const size_t spurious = dec.frames_valid();

    Ax25Encoder enc;
    enc.add_frame(reference_frame_body());
    dec.feed_bits(enc.bits());

    CHECK_EQ(spurious, 0u);
    CHECK_EQ(dec.frames_valid(), 1u);
    CHECK_EQ(sink.frames.size(), 1u);
}

TEST(ax25_decoder_reset_clears_state) {
    Ax25Encoder enc;
    enc.add_frame(reference_frame_body());

    Ax25Decoder dec;
    FrameSink sink;
    sink.attach(dec);

    /* Feed most of the frame, reset mid-flight, then feed the whole thing. */
    const auto& bits = enc.bits();
    dec.feed_bits(bits.data(), bits.size() / 2);
    dec.reset();
    dec.feed_bits(bits);

    CHECK_EQ(sink.frames.size(), 1u);
    CHECK_EQ(dec.frames_valid(), 1u);
}

/* ===========================================================================
 * Bell 202 AFSK
 * ===========================================================================*/

TEST(aprs_afsk_bell202_roundtrip) {
    Ax25Encoder enc;
    /* A long preamble, as a real TNC sends: the slicer's level trackers and the
     * bit clock both need transitions before the frame starts. */
    enc.add_frame(reference_frame_body(), 24, 4);

    constexpr float kAudioRate = 24000.0f;
    const auto audio = dsp::afsk_modulate(enc.bits(), kAudioRate, 1200.0f, 2200.0f,
                                          1200.0f, 0.8f);
    CHECK(audio.size() > 1000u);

    dsp::AfskDemod demod;
    demod.configure(kAudioRate, dsp::AfskDemod::Standard::Bell202);

    std::vector<uint8_t> bits;
    demod.process_audio(audio.data(), audio.size(), bits);

    /* Roughly one bit per 20 samples, give or take the clock's settling. */
    CHECK(bits.size() > enc.bits().size() - 8);
    CHECK(bits.size() < enc.bits().size() + 8);

    Ax25Decoder dec;
    FrameSink sink;
    sink.attach(dec);
    dec.feed_bits(bits);

    CHECK_EQ(sink.frames.size(), 1u);
    if (!sink.frames.empty()) {
        CHECK_STR_EQ(hex(sink.frames[0]), hex(with_fcs(reference_frame_body())));
        const auto packet = packet_from(sink.frames[0]);
        CHECK_STR_EQ(packet.get_stream_text(),
                     "N0CALL-9>APRS,WIDE1-1:!4903.50N/07201.75W-Test");
        CHECK_NEAR(packet.get_position().latitude, 49.0 + 3.50 / 60.0, 1e-5);
    }
}

TEST(aprs_afsk_survives_inverted_audio) {
    /* Some receivers invert the discriminator. NRZI is transition-coded, so an
     * inverted line still decodes; this is what makes AX.25 polarity-agnostic
     * and it must survive the port. */
    Ax25Encoder enc;
    enc.add_frame(reference_frame_body(), 24, 4);

    constexpr float kAudioRate = 24000.0f;

    /* Swapping mark and space inverts the recovered line level. */
    auto inverted_bits = enc.bits();
    for (auto& b : inverted_bits) b = static_cast<uint8_t>(b ^ 1u);
    const auto audio = dsp::afsk_modulate(inverted_bits, kAudioRate, 1200.0f, 2200.0f,
                                          1200.0f, 0.8f);

    dsp::AfskDemod demod;
    demod.configure(kAudioRate, dsp::AfskDemod::Standard::Bell202);

    std::vector<uint8_t> bits;
    demod.process_audio(audio.data(), audio.size(), bits);

    Ax25Decoder dec;
    FrameSink sink;
    sink.attach(dec);
    dec.feed_bits(bits);

    CHECK_EQ(sink.frames.size(), 1u);
    if (!sink.frames.empty())
        CHECK_STR_EQ(hex(sink.frames[0]), hex(with_fcs(reference_frame_body())));
}

/* ===========================================================================
 * Whole channel decoder: IQ in, packets out
 * ===========================================================================*/

TEST(aprs_channel_decoder_from_iq) {
    Ax25Encoder enc;
    enc.add_frame(reference_frame_body(), 24, 4);

    constexpr double kInputRate = 480000.0;   /* decimates by 20 to 24 kHz */
    constexpr double kOffsetHz = 40000.0;     /* signal is above band centre */
    constexpr double kDeviationHz = 3000.0;   /* APRS NBFM */

    const auto audio = dsp::afsk_modulate(enc.bits(), static_cast<float>(kInputRate),
                                          1200.0f, 2200.0f, 1200.0f, 1.0f);
    CHECK(audio.size() > 10000u);

    /* FM-modulate the AFSK audio onto a carrier at +kOffsetHz. */
    std::vector<dsp::cfloat> iq(audio.size());
    double phase = 0.0;
    for (size_t i = 0; i < audio.size(); i++) {
        iq[i] = dsp::cfloat{static_cast<float>(std::cos(phase)),
                            static_cast<float>(std::sin(phase))};
        const double f = kOffsetHz + kDeviationHz * static_cast<double>(audio[i]);
        phase += 2.0 * kPi * f / kInputRate;
        if (phase > kPi) phase -= 2.0 * kPi;
    }

    AprsChannelDecoder decoder;
    decoder.configure(kInputRate, kOffsetHz);
    CHECK(decoder.configured());
    CHECK_EQ(decoder.decimation(), 20u);
    CHECK_NEAR(decoder.channel_rate(), 24000.0, 1e-6);

    std::vector<AprsPacket> packets;
    decoder.on_packet = [&packets](const AprsPacket& p) { packets.push_back(p); };

    /* Deliver in blocks, the way the app does from the sample tap. */
    constexpr size_t kBlock = 4096;
    for (size_t i = 0; i < iq.size(); i += kBlock) {
        const size_t n = std::min(kBlock, iq.size() - i);
        decoder.process(iq.data() + i, n);
    }

    CHECK_EQ(packets.size(), 1u);
    CHECK_EQ(decoder.framer().frames_valid(), 1u);
    if (!packets.empty()) {
        CHECK(packets[0].is_valid_checksum());
        CHECK_STR_EQ(packets[0].get_stream_text(),
                     "N0CALL-9>APRS,WIDE1-1:!4903.50N/07201.75W-Test");
        const AprsPosition pos = packets[0].get_position();
        CHECK_NEAR(pos.latitude, 49.0 + 3.50 / 60.0, 1e-4);
        CHECK_NEAR(pos.longitude, -(72.0 + 1.75 / 60.0), 1e-4);
    }
}

TEST(aprs_channel_decoder_rejects_unconfigured_and_empty_input) {
    AprsChannelDecoder decoder;
    CHECK(!decoder.configured());

    /* Must be a no-op, not a crash. */
    const dsp::cfloat one{1.0f, 0.0f};
    decoder.process(&one, 1);

    decoder.configure(0.0, 0.0);
    CHECK(!decoder.configured());

    decoder.configure(480000.0, 0.0);
    CHECK(decoder.configured());
    decoder.process(nullptr, 100);
    decoder.process(&one, 0);
    CHECK_EQ(decoder.framer().frames_valid(), 0u);
}

TEST(aprs_channel_decoder_rate_selection) {
    AprsChannelDecoder decoder;

    /* Not an integer multiple of 24 kHz: the decimation is rounded and the
     * demodulator is told the rate it actually got. */
    decoder.configure(500000.0, 0.0);
    CHECK_EQ(decoder.decimation(), 21u);
    CHECK_NEAR(decoder.channel_rate(), 500000.0 / 21.0, 1e-6);

    /* An input already at the channel rate must not decimate below 1. */
    decoder.configure(24000.0, 0.0);
    CHECK_EQ(decoder.decimation(), 1u);
    CHECK_NEAR(decoder.channel_rate(), 24000.0, 1e-6);

    decoder.configure(8000.0, 0.0);
    CHECK_EQ(decoder.decimation(), 1u);
}

/* ===========================================================================
 * App wiring
 * ===========================================================================*/

TEST(aprs_region_table_matches_upstream) {
    /* firmware/application/apps/ui_aprs_rx.cpp options_region. */
    static_assert(app::kAprsRegionCount == 10, "upstream offers ten regions");
    CHECK_EQ(app::kAprsRegions[0].frequency, 0u);           /* MAN */
    CHECK_EQ(app::kAprsRegions[1].frequency, 144390000u);   /* NA  */
    CHECK_EQ(app::kAprsRegions[2].frequency, 144575000u);   /* NZ  */
    CHECK_EQ(app::kAprsRegions[3].frequency, 144640000u);   /* JAP */
    CHECK_EQ(app::kAprsRegions[4].frequency, 144740000u);   /* PHI */
    CHECK_EQ(app::kAprsRegions[5].frequency, 144800000u);   /* EUR */
    CHECK_EQ(app::kAprsRegions[6].frequency, 144900000u);   /* THA */
    CHECK_EQ(app::kAprsRegions[7].frequency, 145175000u);   /* AUS */
    CHECK_EQ(app::kAprsRegions[8].frequency, 145570000u);   /* BR  */
    CHECK_EQ(app::kAprsRegions[9].frequency, 145825000u);   /* ISS */
}

TEST(aprs_app_is_registered) {
    const auto* entry = app::AppRegistry::instance().by_id("aprsrx");
    CHECK(entry != nullptr);
    if (entry != nullptr) {
        CHECK_STR_EQ(entry->display_name, "APRS RX");
        CHECK(entry->category == app::Category::Receive);
        CHECK(entry->icon == &ui::bitmap_icon_aprs);
        CHECK(!entry->hardware_limited);
    }
}
