/*
 * mayhem-b200 — Security+ 2.0 encoder tests.
 *
 * Golden packet bytes are generated by running Clayton Smith's upstream
 * secplus encode_v2 (the specification) standalone; the all-zero case is also
 * cross-checked against an independent hand trace of the ORDER=9/INVERT=6
 * scramble path (a clean [110] x 10 interleave -> 0x36DB6DB6). The limits and
 * the Manchester OOK framing are checked directly.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include "test_main.hpp"

#include "ui_secplustx.hpp"

#include <array>
#include <cstdint>
#include <string>

using namespace mb200test;

namespace {

void check_packets(const char* label, uint32_t rolling, uint64_t fixed, uint32_t data,
                   uint8_t ft, const std::array<uint8_t, 8>& e1,
                   const std::array<uint8_t, 8>& e2) {
    uint8_t p1[8]{}, p2[8]{};
    const int8_t rc = app::secplus_encode_v2(rolling, fixed, data, ft, p1, p2);
    CHECK_EQ(rc, int8_t{0});
    for (int i = 0; i < 8; ++i) {
        if (p1[i] != e1[i] || p2[i] != e2[i])
            ::mb200test::report_failure(__FILE__, __LINE__,
                                        std::string{"secplus packet mismatch: "} + label);
    }
}

}  // namespace

TEST(secplus_v2_all_zero) {
    /* Independently hand-traced: ORDER[0]=9, INVERT[0]=6 -> parts_permuted are
     * ~0,~0,0 -> interleave 1,1,0 x 10 into offsets 10..39 -> 0x36DB6DB6. */
    check_packets("all-zero ft0", 0, 0, 0, 0,
                  {0x00, 0x36, 0xDB, 0x6D, 0xB6, 0x00, 0x00, 0x00},
                  {0x00, 0x36, 0xDB, 0x6D, 0xB6, 0x00, 0x00, 0x00});
    check_packets("all-zero ft1", 0, 0, 0, 1,
                  {0x40, 0x36, 0xDB, 0x6D, 0xB6, 0xDB, 0x6D, 0xB6},
                  {0x40, 0x36, 0xDB, 0x6D, 0xB6, 0xDB, 0x6D, 0xB6});
}

TEST(secplus_v2_golden_vectors) {
    /* From upstream secplus encode_v2 (see scratchpad/verify_secplus.cpp). */
    check_packets("vec1 ft0", 0x123456u, 0x89ABCDEull, 0x0u, 0,
                  {0x24, 0x32, 0x8B, 0x29, 0x94, 0x00, 0x00, 0x00},
                  {0x15, 0x8A, 0x9C, 0xF9, 0x69, 0x00, 0x00, 0x00});
    check_packets("vec2 ft1", 0x0ABCDEFu, 0x1234567890ull, 0xDEADBEEFu, 1,
                  {0x49, 0x25, 0xE7, 0xE5, 0x7D, 0x2E, 0x32, 0x1D},
                  {0x60, 0x88, 0x84, 0xC4, 0x11, 0xD6, 0x89, 0x35});
    check_packets("rolling1 ft0", 1, 0, 0, 0,
                  {0x2A, 0xAC, 0xB2, 0x59, 0x6D, 0x00, 0x00, 0x00},
                  {0x28, 0x36, 0xDF, 0x6D, 0xB7, 0x00, 0x00, 0x00});
}

TEST(secplus_v2_limits) {
    uint8_t p1[8]{}, p2[8]{};
    CHECK_EQ(app::secplus_encode_v2(1u << 28, 0, 0, 0, p1, p2), int8_t{-1});
    CHECK_EQ(app::secplus_encode_v2(0, 1ull << 40, 0, 0, p1, p2), int8_t{-1});
    /* Just inside the limits succeeds. */
    CHECK_EQ(app::secplus_encode_v2(0x0FFFFFFFu, 0xFFFFFFFFFFull, 0, 0, p1, p2), int8_t{0});
}

TEST(secplus_packet_manchester_structure) {
    /* No-data packet: 20-bit preamble (40 sym) + 2-bit indicator (4) + 5 bytes
     * (80) + 24 blank = 148 symbols. */
    uint8_t packet[8]{};
    const std::string p = app::secplus_encode_packet(0b00, packet, false);
    CHECK_EQ(p.size(), size_t{148});

    /* Preamble 0x0F...: sixteen 0 bits ("10") then four 1 bits ("01"). */
    std::string preamble;
    for (int i = 0; i < 16; ++i) preamble += "10";
    for (int i = 0; i < 4; ++i) preamble += "01";
    CHECK_STR_EQ(p.substr(0, 40), preamble);

    /* Indicator 0b00 -> "1010". */
    CHECK_STR_EQ(p.substr(40, 4), std::string{"1010"});

    /* Trailing 24-symbol blank. */
    CHECK_STR_EQ(p.substr(148 - 24), std::string(24, '0'));

    /* Data packet is 40 + 4 + 128 + 24 = 196 symbols. */
    const std::string pd = app::secplus_encode_packet(0b01, packet, true);
    CHECK_EQ(pd.size(), size_t{196});
    /* Indicator 0b01 -> a 0 then a 1 -> "10" + "01" = "1001". */
    CHECK_STR_EQ(pd.substr(40, 4), std::string{"1001"});
}

TEST(secplus_bitstream_two_packets) {
    /* Full stream is packet1 + packet2, both no-data here (148 each). */
    const std::string s = app::secplus_encode_bitstream(0, 0, 0, false);
    CHECK_EQ(s.size(), size_t{296});
    /* Out-of-range codes yield an empty stream. */
    CHECK(app::secplus_encode_bitstream(1u << 28, 0, 0, false).empty());
}
