/*
 * mayhem-b200 — icon bitmap set.
 *
 * The firmware keeps its icons as arrays generated by `make_bitmap.py` into
 * firmware/application/bitmap.hpp. The pixel data here is those arrays,
 * unchanged: 1bpp, LSB-first, bit index = y * width + x, which is exactly what
 * host::Display::draw_bitmap consumes.
 *
 * Only the icons the app registry needs are carried over — the upstream header
 * has 130-odd and most of them belong to apps a B200 cannot run.
 *
 * Copyright (C) 2015 Jared Boone, ShareBrained Technology, Inc.
 * Copyright (C) 2016 Furrtek
 * Copyright (C) 2026 mayhem-b200 contributors
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef __HOST_BITMAPS_H__
#define __HOST_BITMAPS_H__

#include "ui.hpp"

#include <cstddef>
#include <string_view>

namespace ui {

/* Menu categories. */
extern const Bitmap bitmap_icon_receivers;
extern const Bitmap bitmap_icon_transmit;
extern const Bitmap bitmap_icon_transceivers;
extern const Bitmap bitmap_icon_scanner;
extern const Bitmap bitmap_icon_capture;
extern const Bitmap bitmap_icon_replay;
extern const Bitmap bitmap_icon_looking;
extern const Bitmap bitmap_icon_utilities;
extern const Bitmap bitmap_icon_games;
extern const Bitmap bitmap_icon_setup;

/* Receive apps. */
extern const Bitmap bitmap_icon_adsb;
extern const Bitmap bitmap_icon_ais;
extern const Bitmap bitmap_icon_aprs;
extern const Bitmap bitmap_icon_speaker;
extern const Bitmap bitmap_icon_btle;
extern const Bitmap bitmap_icon_pocsag;
extern const Bitmap bitmap_icon_sonde;
extern const Bitmap bitmap_icon_search;
extern const Bitmap bitmap_icon_remote;
extern const Bitmap bitmap_icon_thermometer;

/* Transmit and transceive apps. */
extern const Bitmap bitmap_icon_rds;
extern const Bitmap bitmap_icon_touchtunes;
extern const Bitmap bitmap_icon_microphone;

/* Utilities. */
extern const Bitmap bitmap_icon_dir;
extern const Bitmap bitmap_icon_freqman;
extern const Bitmap bitmap_icon_trim;
extern const Bitmap bitmap_icon_notepad;
extern const Bitmap bitmap_icon_debug;
extern const Bitmap bitmap_icon_peripherals_details;

/* Navigation. */
extern const Bitmap bitmap_icon_previous;

/* Fallback for a grid entry with no icon of its own. Not an upstream bitmap —
 * the firmware reuses bitmap_icon_utilities for that job; this is a purpose-made
 * 16x16 tile so a missing icon is visibly a placeholder rather than a wrench. */
extern const Bitmap bitmap_icon_generic;

/* Every icon this file exports, so callers (and the tests) can enumerate them.
 * `data_size` is the byte length of the underlying array, which lets a caller
 * check it against the declared Size. */
struct NamedBitmap {
    const char* name;
    const Bitmap* bitmap;
    size_t data_size;
};

const NamedBitmap* icon_table();
size_t icon_table_size();

/* Looks an icon up by its short name ("adsb", "previous", ...).
 * Returns nullptr when the name is unknown — callers that need something to
 * draw should fall back to &bitmap_icon_generic themselves. */
const Bitmap* icon_by_name(std::string_view name);

}  // namespace ui

#endif /*__HOST_BITMAPS_H__*/
